server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML #LEGACYHTML5
captcha:
  slider:
    expire: 10000
    obfuscate: false
    cache:
      enabled: true
      cache-size: 20
    secondary:
      enabled: true